export const LIST_CITY = [
  { label: "Hồ Chí Minh", value: "Ho Chi Minh City" },
  { label: "Hà Nội", value: "Hanoi" },
  { label: "Đà Nẵng", value: "Da Nang" },
  { label: "Hải Phòng", value: "Hai Phong" },
  { label: "Cần Thơ", value: "Can Tho" },

  { label: "Hạ Long", value: "Ha Long" },
  { label: "Thái Nguyên", value: "Thai Nguyen" },
  { label: "Nam Định", value: "Nam Dinh" },
  { label: "Vinh", value: "Vinh" },
  { label: "Ninh Bình", value: "Ninh Binh" },
  { label: "Hà Giang", value: "Ha Giang" },
  { label: "Cao Bằng", value: "Cao Bang" },
  { label: "Lạng Sơn", value: "Lang Son" },
  { label: "Lào Cai", value: "Lao Cai" },
  { label: "Yên Bái", value: "Yen Bai" },
  { label: "Điện Biên Phủ", value: "Dien Bien Phu" },
  { label: "Lai Châu", value: "Lai Chau" },
  { label: "Sơn La", value: "Son La" },
  { label: "Hòa Bình", value: "Hoa Binh" },
  { label: "Phú Thọ", value: "Phu Tho" },
  { label: "Tuyên Quang", value: "Tuyen Quang" },
  { label: "Bắc Kạn", value: "Bac Kan" },
  { label: "Bắc Giang", value: "Bac Giang" },
  { label: "Bắc Ninh", value: "Bac Ninh" },
  { label: "Quảng Ninh", value: "Quang Ninh" },
  { label: "Hưng Yên", value: "Hung Yen" },
  { label: "Hà Nam", value: "Ha Nam" },
  { label: "Thái Bình", value: "Thai Binh" },

  // Miền Trung
  { label: "Huế", value: "Hue" },
  { label: "Hội An", value: "Hoi An" },
  { label: "Thanh Hóa", value: "Thanh Hoa" },
  { label: "Nghệ An", value: "Nghe An" },
  { label: "Hà Tĩnh", value: "Ha Tinh" },
  { label: "Quảng Bình", value: "Quang Binh" },
  { label: "Quảng Trị", value: "Quang Tri" },
  { label: "Quảng Nam", value: "Quang Nam" },
  { label: "Quảng Ngãi", value: "Quang Ngai" },
  { label: "Bình Định", value: "Binh Dinh" },
  { label: "Phú Yên", value: "Phu Yen" },
  { label: "Khánh Hòa", value: "Khanh Hoa" },
  { label: "Nha Trang", value: "Nha Trang" },
  { label: "Đà Lạt", value: "Dalat" },
  { label: "Lâm Đồng", value: "Lam Dong" },
  { label: "Ninh Thuận", value: "Ninh Thuan" },
  { label: "Bình Thuận", value: "Binh Thuan" },
  { label: "Kon Tum", value: "Kon Tum" },
  { label: "Gia Lai", value: "Gia Lai" },
  { label: "Đắk Lắk", value: "Dak Lak" },
  { label: "Đắk Nông", value: "Dak Nong" },

  { label: "Vũng Tàu", value: "Vung Tau" },
  { label: "Biên Hòa", value: "Bien Hoa" },
  { label: "Đồng Nai", value: "Dong Nai" },
  { label: "Bình Dương", value: "Binh Duong" },
  { label: "Thủ Dầu Một", value: "Thu Dau Mot" },
  { label: "Tây Ninh", value: "Tay Ninh" },
  { label: "Bình Phước", value: "Binh Phuoc" },
  { label: "Long An", value: "Long An" },
  { label: "Tân An", value: "Tan An" },
  { label: "Đồng Tháp", value: "Dong Thap" },
  { label: "An Giang", value: "An Giang" },
  { label: "Long Xuyên", value: "Long Xuyen" },
  { label: "Kiên Giang", value: "Kien Giang" },
  { label: "Rạch Giá", value: "Rach Gia" },
  { label: "Cà Mau", value: "Ca Mau" },
  { label: "Bạc Liêu", value: "Bac Lieu" },
  { label: "Sóc Trăng", value: "Soc Trang" },
  { label: "Trà Vinh", value: "Tra Vinh" },
  { label: "Vĩnh Long", value: "Vinh Long" },
  { label: "Bến Tre", value: "Ben Tre" },
  { label: "Tiền Giang", value: "Tien Giang" },
  { label: "Mỹ Tho", value: "My Tho" },
  { label: "Hậu Giang", value: "Hau Giang" },

  { label: "Phú Quốc", value: "Phu Quoc" },
  { label: "Côn Đảo", value: "Con Dao" },
];
