packages:
  - "apps/*"
  - "packages/*"
packageExtensions:
  "@gorhom/bottom-sheet@5.2.14":
    peerDependencies:
      react-native-reanimated: ">=3.16.0 || >=4.0.0"
peerDependencyRules:
  allowedVersions:
    "@gorhom/bottom-sheet@5.2.14>react-native-reanimated": "4.3.1"
